# =============================================================================
# dbt Profiles - Trino/Iceberg Connection
# =============================================================================

trino_iceberg:
  target: dev
  outputs:
    dev:
      type: trino
      method: none
      host: "{{ env_var('TRINO_HOST', 'trino') }}"
      port: "{{ env_var('TRINO_PORT', '8080') | int }}"
      user: "{{ env_var('TRINO_USER', 'dbt') }}"
      catalog: iceberg
      schema: silver
      threads: 4
      http_scheme: http
      session_properties:
        query_max_run_time: 30m
    
    prod:
      type: trino
      method: none
      host: "{{ env_var('TRINO_HOST', 'trino') }}"
      port: "{{ env_var('TRINO_PORT', '8080') | int }}"
      user: "{{ env_var('TRINO_USER', 'dbt') }}"
      catalog: iceberg
      schema: silver
      threads: 8
      http_scheme: http

